spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.application.name=medistock

spring.datasource.url=jdbc:postgresql://ep-lively-rice-ag7y48kz-pooler.c-2.eu-central-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_iuRrSnU0x2WI
spring.datasource.driver-class-name=org.postgresql.Driver
